/*
Thomas Griffin
Assignment 4
griff073@cougars.csusm.edu
last editied on: 5/7/15
CS211
SEC10-20315
Description:This program will create a linked list of
families.The list is generated by running through a transaction
file called "transactionfile.txt". Based on the command the 
program takes in from the transaction file it will execute a 
certain function. Like the command AddHusband will take
in the necessary information and add a object of type husband
to the top of the linked list. All output will be displayed
on the screen.
*/
#include "Family.h"
using namespace std;
int main()
{
  Family USAFamilies;
  USAFamilies.ReadTransactionFile();
  return 0;
}//end main 

